/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeLayoutRouteImport } from './routes/(home)/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as homeDocsRouteImport } from './routes/(home)/docs'

const homeLayoutRoute = homeLayoutRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeDocsRoute = homeDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => homeLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof homeDocsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof homeDocsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(home)': typeof homeLayoutRouteWithChildren
  '/(home)/docs': typeof homeDocsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs'
  id: '__root__' | '/' | '/(home)' | '/(home)/docs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  homeLayoutRoute: typeof homeLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/docs': {
      id: '/(home)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof homeDocsRouteImport
      parentRoute: typeof homeLayoutRoute
    }
  }
}

interface homeLayoutRouteChildren {
  homeDocsRoute: typeof homeDocsRoute
}

const homeLayoutRouteChildren: homeLayoutRouteChildren = {
  homeDocsRoute: homeDocsRoute,
}

const homeLayoutRouteWithChildren = homeLayoutRoute._addFileChildren(
  homeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  homeLayoutRoute: homeLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
