/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeLayoutRouteImport } from './routes/(home)/layout'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as documentationDocsRouteImport } from './routes/(documentation)/docs'

const homeLayoutRoute = homeLayoutRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeLayoutRoute,
} as any)
const documentationDocsRoute = documentationDocsRouteImport.update({
  id: '/(documentation)/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/docs': typeof documentationDocsRoute
  '/': typeof homeIndexRoute
}
export interface FileRoutesByTo {
  '/docs': typeof documentationDocsRoute
  '/': typeof homeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeLayoutRouteWithChildren
  '/(documentation)/docs': typeof documentationDocsRoute
  '/(home)/': typeof homeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/docs' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/docs' | '/'
  id: '__root__' | '/(home)' | '/(documentation)/docs' | '/(home)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeLayoutRoute: typeof homeLayoutRouteWithChildren
  documentationDocsRoute: typeof documentationDocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof homeLayoutRoute
    }
    '/(documentation)/docs': {
      id: '/(documentation)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof documentationDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface homeLayoutRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
}

const homeLayoutRouteChildren: homeLayoutRouteChildren = {
  homeIndexRoute: homeIndexRoute,
}

const homeLayoutRouteWithChildren = homeLayoutRoute._addFileChildren(
  homeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeLayoutRoute: homeLayoutRouteWithChildren,
  documentationDocsRoute: documentationDocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
